version: "2.0"
services:

  kicadlisp:
    container_name: "kicadlisp"
    image: node
    command: "/app/runincontainer.sh"
    working_dir: /app
    ports:
      - "11090:5173"
    volumes:
      - "/opt/projects/kicadlisp/frontend:/app"
